- name: "Creating namespace {{ namespace_name }} on {{ target_hosts }} host group"
  hosts: "{{ target_hosts }}"
  connection: local
  tasks:
  - name: "Enable ClusterProxy Addon"
    ocmplus.cm.managedcluster_addon:
      state: present
      addon_name: cluster-proxy
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      wait: True
      timeout: 60
  - name: "Enable Managed-ServiceAccount Addon"
    ocmplus.cm.managedcluster_addon:
      state: present
      addon_name: managed-serviceaccount
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      wait: True
      timeout: 60
  - name: "Get ClusterProxy URL for {{ hostvars[inventory_hostname].cluster_name }}"
    ocmplus.cm.cluster_proxy:
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      wait: True
      timeout: 60
    register: cluster_proxy_url
  - name: debug
    debug:
      msg: "{{ cluster_proxy_url.cluster_url }}"

  - name: "Get managed ServiceAccount token for {{ hostvars[inventory_hostname].cluster_name }}"
    ocmplus.cm.managed_serviceaccount:
      name: test-managed-serviceaccount
      state: present
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      wait: True
      timeout: 60
      ttl_seconds_after_creation:  "{{ ttl_seconds | default(60) }}"
    register: managed_serviceaccount

  - name: debug
    debug:
      msg: "managed_serviceaccount_name: {{ managed_serviceaccount.name }}"

  - name: "Configure ServiceAccount RBAC for {{ hostvars[inventory_hostname].cluster_name }}"
    ocmplus.cm.managed_serviceaccount_rbac:
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      managed_serviceaccount_name: "{{ managed_serviceaccount.name }}"
      rbac_template: rbac/clusterrolebinding.yml
      wait: True
      timeout: 60
    register: result
    ignore_errors: true
    when: hostvars[inventory_hostname].cluster_name != skipped_rbac_cluster_name|default('')

  - name: "Creating namespace {{ namespace_name }} on {{ hostvars[inventory_hostname].cluster_name }}"
    kubernetes.core.k8s:
      state: present
      host: "{{ cluster_proxy_url.cluster_url }}"
      validate_certs: no
      api_key: "{{managed_serviceaccount.token}}"
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{ namespace_name }}"
          
  - name: "Removing managed ServiceAccount {{ managed_serviceaccount.managed_serviceaccount.name }} for {{ hostvars[inventory_hostname].cluster_name }}"
    ocmplus.cm.managed_serviceaccount:
      state: absent
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
      name: "{{ managed_serviceaccount.managed_serviceaccount.name }}"
      wait: True
      timeout: 60
