- name: "Enable addons on hub"
  hosts: "{{ target_hosts }}"
  connection: local
  tasks:
  - name: "enable managed-serviceaccount"
    ocmplus.cm.cluster_management_addon:
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      wait: True
      timeout: 60
      addon_name: managed-serviceaccount
      state: present
  - name: "enable cluster-proxy"
    ocmplus.cm.cluster_management_addon:
      hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
      wait: True
      timeout: 60
      addon_name: cluster-proxy
      state: present
